export type Category =
  | "Syringes & Needles"
  | "Pipettes & Tips"
  | "PPE"
  | "Reagents & Chemicals"
  | "Glassware"
  | "Instruments"
  | "Dissection & Biology"
  | "Storage & Containers";

export type Product = {
  sku: string;
  name: string;
  category: Category;
  price: number;
  unit: string;
  description: string;
  inStock: boolean;
};

export const CATEGORIES: Category[] = [
  "Syringes & Needles",
  "Pipettes & Tips",
  "PPE",
  "Reagents & Chemicals",
  "Glassware",
  "Instruments",
  "Dissection & Biology",
  "Storage & Containers",
];

export const CATEGORY_EMOJI: Record<Category, string> = {
  "Syringes & Needles": "💉",
  "Pipettes & Tips": "🧪",
  "PPE": "🥼",
  "Reagents & Chemicals": "⚗️",
  "Glassware": "🔬",
  "Instruments": "⚙️",
  "Dissection & Biology": "🧫",
  "Storage & Containers": "📦",
};

export const CATEGORY_COLOR: Record<Category, string> = {
  "Syringes & Needles": "bg-blue-50 text-blue-700",
  "Pipettes & Tips": "bg-teal-50 text-teal-700",
  "PPE": "bg-orange-50 text-orange-700",
  "Reagents & Chemicals": "bg-purple-50 text-purple-700",
  "Glassware": "bg-cyan-50 text-cyan-700",
  "Instruments": "bg-gray-100 text-gray-700",
  "Dissection & Biology": "bg-green-50 text-green-700",
  "Storage & Containers": "bg-red-50 text-red-700",
};

export const PRODUCTS: Product[] = [
  // ── SYRINGES & NEEDLES ──────────────────────────────────────────────────
  {
    sku: "SYR-001",
    name: "BD Insulin Syringe 1mL 28G × ½\"",
    category: "Syringes & Needles",
    price: 12.50,
    unit: "Box/100",
    description: "Ultra-fine 28G needle for subcutaneous injections. Low-dead-space design maximises dose accuracy.",
    inStock: true,
  },
  {
    sku: "SYR-002",
    name: "BD Luer-Lock Syringe 3mL",
    category: "Syringes & Needles",
    price: 9.99,
    unit: "Box/50",
    description: "Twist-lock tip prevents needle detachment during injection. Clear barrel for easy dose reading.",
    inStock: true,
  },
  {
    sku: "SYR-003",
    name: "BD Luer-Lock Syringe 5mL",
    category: "Syringes & Needles",
    price: 11.50,
    unit: "Box/50",
    description: "Standard 5mL luer-lock syringe. Smooth plunger, bold graduation markings.",
    inStock: true,
  },
  {
    sku: "SYR-004",
    name: "BD Luer-Lock Syringe 10mL",
    category: "Syringes & Needles",
    price: 15.99,
    unit: "Box/25",
    description: "High-volume 10mL syringe with luer-lock tip. Suitable for reconstituting lyophilised reagents.",
    inStock: true,
  },
  {
    sku: "SYR-005",
    name: "BD Luer-Lock Syringe 20mL",
    category: "Syringes & Needles",
    price: 19.50,
    unit: "Box/25",
    description: "Large-format 20mL syringe for bulk dispensing. Ergonomic finger grips reduce hand fatigue.",
    inStock: true,
  },
  {
    sku: "SYR-006",
    name: "Hypodermic Needle 18G × 1½\"",
    category: "Syringes & Needles",
    price: 7.50,
    unit: "Box/100",
    description: "Standard 18G thin-wall needle for drawing viscous solutions. Individually blister-packed.",
    inStock: true,
  },
  {
    sku: "SYR-007",
    name: "Hypodermic Needle 21G × 1½\"",
    category: "Syringes & Needles",
    price: 7.50,
    unit: "Box/100",
    description: "21G general-purpose injection needle. Tri-bevel tip for smooth tissue penetration.",
    inStock: true,
  },
  {
    sku: "SYR-008",
    name: "Syringe Filter 0.22 μm PVDF",
    category: "Syringes & Needles",
    price: 48.00,
    unit: "Pack/50",
    description: "Sterile 0.22 μm PVDF membrane filter for sterilisation of aqueous and mildly organic solutions.",
    inStock: true,
  },

  // ── PIPETTES & TIPS ─────────────────────────────────────────────────────
  {
    sku: "PIP-001",
    name: "Eppendorf Research Plus 10 μL",
    category: "Pipettes & Tips",
    price: 88.00,
    unit: "Each",
    description: "Single-channel air-displacement pipette. Ergonomic design, autoclavable lower part, ±1% accuracy.",
    inStock: true,
  },
  {
    sku: "PIP-002",
    name: "Eppendorf Research Plus 200 μL",
    category: "Pipettes & Tips",
    price: 88.00,
    unit: "Each",
    description: "Single-channel pipette optimised for the 20–200 μL range. Light plunger force reduces RSI risk.",
    inStock: true,
  },
  {
    sku: "PIP-003",
    name: "Eppendorf Research Plus 1000 μL",
    category: "Pipettes & Tips",
    price: 92.00,
    unit: "Each",
    description: "Handles volumes 100–1000 μL. Fixed angle tip ejector for consistent ejection force.",
    inStock: true,
  },
  {
    sku: "PIP-004",
    name: "Gilson PIPETMAN P200",
    category: "Pipettes & Tips",
    price: 95.00,
    unit: "Each",
    description: "The gold-standard pipette. Adjustable 20–200 μL, stainless-steel plunger, NIST-traceable calibration.",
    inStock: true,
  },
  {
    sku: "PIP-005",
    name: "8-Channel Multichannel Pipette 20–200 μL",
    category: "Pipettes & Tips",
    price: 285.00,
    unit: "Each",
    description: "Process an entire 96-well plate row at once. Uniform spring tension across all channels.",
    inStock: false,
  },
  {
    sku: "PIP-006",
    name: "Pipette Tips 10 μL Low-Retention",
    category: "Pipettes & Tips",
    price: 13.99,
    unit: "Rack/96",
    description: "Hydrophobic surface minimises sample retention. Pre-racked and certified RNase/DNase-free.",
    inStock: true,
  },
  {
    sku: "PIP-007",
    name: "Pipette Tips 200 μL Universal Fit",
    category: "Pipettes & Tips",
    price: 11.99,
    unit: "Rack/96",
    description: "Fits Eppendorf, Gilson, Rainin, and most other major brands. Autoclavable rack.",
    inStock: true,
  },
  {
    sku: "PIP-008",
    name: "Pipette Tips 1000 μL Universal Fit",
    category: "Pipettes & Tips",
    price: 14.99,
    unit: "Rack/96",
    description: "Wide-bore 1000 μL tip for viscous samples. Certified DNase/RNase/pyrogen-free.",
    inStock: true,
  },

  // ── PPE ─────────────────────────────────────────────────────────────────
  {
    sku: "PPE-001",
    name: "Nitrile Examination Gloves — Small",
    category: "PPE",
    price: 9.99,
    unit: "Box/100",
    description: "Powder-free, latex-free nitrile. 4.5 mil thickness, textured fingertips, AQL 1.5.",
    inStock: true,
  },
  {
    sku: "PPE-002",
    name: "Nitrile Examination Gloves — Medium",
    category: "PPE",
    price: 9.99,
    unit: "Box/100",
    description: "Most-ordered size. Excellent chemical resistance, ambidextrous design.",
    inStock: true,
  },
  {
    sku: "PPE-003",
    name: "Nitrile Examination Gloves — Large",
    category: "PPE",
    price: 9.99,
    unit: "Box/100",
    description: "Same 4.5 mil nitrile construction. Beaded cuff prevents roll-down.",
    inStock: true,
  },
  {
    sku: "PPE-004",
    name: "Nitrile Examination Gloves — XL",
    category: "PPE",
    price: 10.99,
    unit: "Box/100",
    description: "Extended cuff for additional wrist protection. AQL 1.5 certified.",
    inStock: true,
  },
  {
    sku: "PPE-005",
    name: "Chemical Splash Safety Goggles",
    category: "PPE",
    price: 8.50,
    unit: "Each",
    description: "Indirect-vent goggles with anti-fog coating. Fits over prescription glasses. ANSI Z87.1.",
    inStock: true,
  },
  {
    sku: "PPE-006",
    name: "Anti-Fog Safety Glasses",
    category: "PPE",
    price: 5.99,
    unit: "Each",
    description: "Wrap-around side shields, adjustable temples. Lightweight polycarbonate lens. ANSI Z87+.",
    inStock: true,
  },
  {
    sku: "PPE-007",
    name: "Disposable Lab Coat — S/M",
    category: "PPE",
    price: 26.99,
    unit: "Each",
    description: "SMS fabric, fluid-resistant, snap-front closure. Suitable for single-shift use in BSL-2 labs.",
    inStock: true,
  },
  {
    sku: "PPE-008",
    name: "Full Face Shield",
    category: "PPE",
    price: 16.99,
    unit: "Each",
    description: "Adjustable ratchet headgear, 8\" × 15.5\" clear polycarbonate shield. ANSI Z87.1.",
    inStock: true,
  },

  // ── REAGENTS & CHEMICALS ────────────────────────────────────────────────
  {
    sku: "REA-001",
    name: "Ethanol 70% (v/v) 500 mL",
    category: "Reagents & Chemicals",
    price: 14.50,
    unit: "Bottle",
    description: "Ready-to-use 70% ethanol for surface decontamination and equipment sterilisation.",
    inStock: true,
  },
  {
    sku: "REA-002",
    name: "Ethanol 70% (v/v) 1 L",
    category: "Reagents & Chemicals",
    price: 23.99,
    unit: "Bottle",
    description: "Economy 1 L size. Same formulation as 500 mL; better value for high-throughput labs.",
    inStock: true,
  },
  {
    sku: "REA-003",
    name: "PBS Buffer 1× 500 mL",
    category: "Reagents & Chemicals",
    price: 12.00,
    unit: "Bottle",
    description: "Ready-to-use phosphate-buffered saline, pH 7.4 ± 0.05. Sterile-filtered, endotoxin-tested.",
    inStock: true,
  },
  {
    sku: "REA-004",
    name: "PBS Buffer 10× Concentrate 1 L",
    category: "Reagents & Chemicals",
    price: 29.99,
    unit: "Bottle",
    description: "10× concentrate yields 10 L of working solution. Reduces storage footprint.",
    inStock: true,
  },
  {
    sku: "REA-005",
    name: "Sterile Distilled Water 1 L",
    category: "Reagents & Chemicals",
    price: 5.99,
    unit: "Bottle",
    description: "Sterile 0.22 μm-filtered water for reagent preparation. < 1 EU/mL endotoxin.",
    inStock: true,
  },
  {
    sku: "REA-006",
    name: "LB Agar Plates — Ready to Use",
    category: "Reagents & Chemicals",
    price: 38.00,
    unit: "Pack/20",
    description: "Pre-poured, quality-controlled LB agar plates. Store at 4 °C; 8-week shelf life.",
    inStock: true,
  },
  {
    sku: "REA-007",
    name: "Agarose LE Powder 100 g",
    category: "Reagents & Chemicals",
    price: 44.99,
    unit: "Jar",
    description: "Low-EEO agarose for standard DNA/RNA gel electrophoresis. Melting point 87–89 °C.",
    inStock: true,
  },
  {
    sku: "REA-008",
    name: "DMSO Anhydrous ≥99.9% 100 mL",
    category: "Reagents & Chemicals",
    price: 19.99,
    unit: "Bottle",
    description: "Anhydrous dimethyl sulfoxide for cryopreservation and drug solubilisation. Sure/Seal bottle.",
    inStock: true,
  },

  // ── GLASSWARE ───────────────────────────────────────────────────────────
  {
    sku: "GLA-001",
    name: "Borosilicate Beaker 100 mL",
    category: "Glassware",
    price: 3.99,
    unit: "Each",
    description: "Heavy-wall borosilicate glass, graduated. Withstands repeated autoclaving and open-flame heating.",
    inStock: true,
  },
  {
    sku: "GLA-002",
    name: "Borosilicate Beaker 250 mL",
    category: "Glassware",
    price: 4.99,
    unit: "Each",
    description: "Griffin-style low-form beaker. Uniform wall thickness for even heat distribution.",
    inStock: true,
  },
  {
    sku: "GLA-003",
    name: "Borosilicate Beaker 500 mL",
    category: "Glassware",
    price: 6.99,
    unit: "Each",
    description: "Large-format beaker ideal for reagent preparation and stirring large volumes.",
    inStock: true,
  },
  {
    sku: "GLA-004",
    name: "Erlenmeyer Flask 250 mL",
    category: "Glassware",
    price: 5.99,
    unit: "Each",
    description: "Narrow neck minimises evaporation during heating. Graduated, borosilicate glass.",
    inStock: true,
  },
  {
    sku: "GLA-005",
    name: "Erlenmeyer Flask 500 mL",
    category: "Glassware",
    price: 7.99,
    unit: "Each",
    description: "Wide-mouth 500 mL flask. Suitable for shaker culture and reagent prep.",
    inStock: true,
  },
  {
    sku: "GLA-006",
    name: "Graduated Cylinder 100 mL",
    category: "Glassware",
    price: 9.50,
    unit: "Each",
    description: "Class B borosilicate graduated cylinder. Hexagonal base for stability.",
    inStock: true,
  },
  {
    sku: "GLA-007",
    name: "Petri Dish 100 mm Borosilicate",
    category: "Glassware",
    price: 3.50,
    unit: "Each",
    description: "Reusable borosilicate petri dish with lid. Autoclavable, for microbiology and cell culture.",
    inStock: true,
  },
  {
    sku: "GLA-008",
    name: "Plain Microscope Slides",
    category: "Glassware",
    price: 8.99,
    unit: "Box/72",
    description: "Pre-cleaned 75 × 25 mm soda-lime glass slides. 1 mm thickness, ground edges.",
    inStock: true,
  },

  // ── INSTRUMENTS ─────────────────────────────────────────────────────────
  {
    sku: "INS-001",
    name: "Digital pH Meter with Electrode",
    category: "Instruments",
    price: 89.99,
    unit: "Each",
    description: "±0.01 pH accuracy, automatic temperature compensation. Includes BNC electrode and buffer sachets.",
    inStock: true,
  },
  {
    sku: "INS-002",
    name: "Hot Plate Magnetic Stirrer",
    category: "Instruments",
    price: 249.00,
    unit: "Each",
    description: "250 °C max temperature, 100–1500 RPM, ceramic plate. External temperature probe port.",
    inStock: true,
  },
  {
    sku: "INS-003",
    name: "Vortex Mixer — Fixed Speed",
    category: "Instruments",
    price: 185.00,
    unit: "Each",
    description: "2800 RPM fixed-speed vortexer. Touch-activated mode. Universal cup-head attachment.",
    inStock: true,
  },
  {
    sku: "INS-004",
    name: "Mini Centrifuge 6000 RPM",
    category: "Instruments",
    price: 299.00,
    unit: "Each",
    description: "Compact personal centrifuge. Holds 6 × 1.5/2 mL or 2 × 15 mL tubes. Push-button operation.",
    inStock: false,
  },
  {
    sku: "INS-005",
    name: "Digital Thermometer −50–200 °C",
    category: "Instruments",
    price: 34.99,
    unit: "Each",
    description: "Waterproof K-type thermocouple thermometer. 0.1 °C resolution. Hold and max/min functions.",
    inStock: true,
  },
  {
    sku: "INS-006",
    name: "Magnetic Stir Bar Set — Assorted",
    category: "Instruments",
    price: 22.50,
    unit: "Pack/10",
    description: "PTFE-coated stir bars in 5 sizes (8–50 mm). Chemically inert, autoclavable.",
    inStock: true,
  },
  {
    sku: "INS-007",
    name: "Lab Timer — 3-Channel Digital",
    category: "Instruments",
    price: 18.99,
    unit: "Each",
    description: "Three independent countdown/up timers. Loud alarm, magnetic backing, belt clip.",
    inStock: true,
  },
  {
    sku: "INS-008",
    name: "Spatula & Weighing Spoon Set (6-piece)",
    category: "Instruments",
    price: 14.99,
    unit: "Set",
    description: "Polished stainless-steel spatulas and spoons. Autoclavable, chemical-resistant.",
    inStock: true,
  },

  // ── DISSECTION & BIOLOGY ────────────────────────────────────────────────
  {
    sku: "DIS-001",
    name: "Student Dissection Kit — 10-piece",
    category: "Dissection & Biology",
    price: 24.99,
    unit: "Each",
    description: "Includes scalpel, scissors, forceps, probes, and pins. Stainless steel in zip pouch.",
    inStock: true,
  },
  {
    sku: "DIS-002",
    name: "Professional Dissection Kit — 15-piece",
    category: "Dissection & Biology",
    price: 42.99,
    unit: "Each",
    description: "Extended set with bone saw, teasing needle, and iris scissors. Autoclavable stainless steel.",
    inStock: false,
  },
  {
    sku: "DIS-003",
    name: "Specimen Jar with Lid — 500 mL",
    category: "Dissection & Biology",
    price: 13.50,
    unit: "Each",
    description: "Wide-mouth glass jar with screw-top lid for fixative storage of specimens.",
    inStock: true,
  },
  {
    sku: "DIS-004",
    name: "Specimen Jar with Lid — 1000 mL",
    category: "Dissection & Biology",
    price: 17.99,
    unit: "Each",
    description: "Large-format specimen jar for bigger specimens or bulk fixative storage.",
    inStock: true,
  },
  {
    sku: "DIS-005",
    name: "Stainless Forceps — Straight 4\"",
    category: "Dissection & Biology",
    price: 6.99,
    unit: "Each",
    description: "Standard dissecting forceps with fine serrated tips. Autoclavable 304 stainless steel.",
    inStock: true,
  },
  {
    sku: "DIS-006",
    name: "Scalpel Blades #10 — Box/100",
    category: "Dissection & Biology",
    price: 14.99,
    unit: "Box/100",
    description: "Sterile surgical steel blades for #3 handle. Individually foil-wrapped.",
    inStock: true,
  },

  // ── STORAGE & CONTAINERS ────────────────────────────────────────────────
  {
    sku: "STO-001",
    name: "Cryogenic Vials 2.0 mL",
    category: "Storage & Containers",
    price: 29.00,
    unit: "Pack/100",
    description: "External-thread cryovials with O-ring seal. Withstand −196 °C liquid nitrogen storage.",
    inStock: true,
  },
  {
    sku: "STO-002",
    name: "Conical Centrifuge Tubes 15 mL",
    category: "Storage & Containers",
    price: 22.50,
    unit: "Pack/50",
    description: "Polypropylene, graduated, leak-proof screw cap. RNase/DNase/endotoxin-free.",
    inStock: true,
  },
  {
    sku: "STO-003",
    name: "Conical Centrifuge Tubes 50 mL",
    category: "Storage & Containers",
    price: 29.99,
    unit: "Pack/25",
    description: "High-clarity 50 mL tubes withstand 10,000 × g. Snap-on dual-position rack compatible.",
    inStock: true,
  },
  {
    sku: "STO-004",
    name: "Microcentrifuge Tubes 1.5 mL",
    category: "Storage & Containers",
    price: 9.99,
    unit: "Pack/500",
    description: "Snap-cap natural 1.5 mL tubes. Withstand 25,000 × g, −80 °C to 121 °C.",
    inStock: true,
  },
  {
    sku: "STO-005",
    name: "Microcentrifuge Tubes 0.5 mL",
    category: "Storage & Containers",
    price: 9.99,
    unit: "Pack/500",
    description: "Low-retention surface minimises sample adhesion. Graduated, flat-top snap cap.",
    inStock: true,
  },
  {
    sku: "STO-006",
    name: "Polypropylene Freezer Box 81-Well",
    category: "Storage & Containers",
    price: 9.99,
    unit: "Each",
    description: "9 × 9 grid holds 81 × 1.5/2 mL cryovials. Numbered grid, stackable design.",
    inStock: true,
  },
];
